# Welcome to Jekyll!

# Website settings
title: "SDEV"
description: "SDEV on GITBUB"
keywords: "sdev,steve,blog,Jekyll,github,gh-pages"

baseurl: "/"
url: "http://sdev.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'SDEV'
  first_name: 'SDEV'
  last_name: ''
  email: 'lslc.atwork@gmail.com'
  facebook_username: 'stevelongchen'
  linkedin_username: 'stevelongchen'
  github_username: 'sdev'
  head_img: 'static/img/landing/sdev_200x200.jpg'

# landing page
landing:
  home: 'Home'
  about: 'About'
  projects: 'Projects'
  contact: 'Contact'

# my projects
project:
  pebble: 
    name: 'sFace'
    url: '/sdev/PLACEHOLDER'
    img: 'static/img/landing/pebble_logo.jpg'
  firefox: 
    name: 'sMateBlack'
    url: '/sdev/PLACEHOLDER'
    img: 'static/img/landing/firefox_logo_200x188.jpg'
  android: 
    name: 'sAlarm'
    url: '/sdev/PLACEHOLDER'
    img: 'static/img/landing/Android_Robot_170x198.png'
  jnippet: 
    name: 'Jnippet'
    url: '/sdev/PLACEHOLDER'
    img: 'static/img/landing/Java_logo.png'
  lyncode: 
    name: 'Lyncode'
    url: '/sdev/PLACEHOLDER'
    img: 'static/img/landing/Lyncode_189x200.png'
  pnippet: 
    name: 'Pnippet'
    url: '/sdev/PLACEHOLDER'
    img: 'static/img/landing/Python_logo_200x200.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# blog img path
img_path: '/static/img/blog'

# Build settings
encoding: "utf-8"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge